name: Selenium Automation Tests

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

  schedule:
    # 11:00 PM IST = 5:30 PM UTC
    - cron: '30 17 * * *'

jobs:

  # =========================
  # SMOKE TEST JOB
  # =========================
  smoke-tests:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Check Java version
        run: java -version

      - name: Check Maven version
        run: mvn -version

      - name: Run Smoke Tests
        run: mvn clean test "-DsuiteXmlFile=testng-smoke.xml"

      - name: Upload Smoke Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: smoke-test-reports
          path: |
            target/surefire-reports/
            target/ExtentReport.html
            screenshot/


  # =========================
  # REGRESSION TEST JOB
  # =========================
  regression-tests:

    needs: smoke-tests
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Check Java version
        run: java -version

      - name: Check Maven version
        run: mvn -version

      - name: Run Regression Tests
        run: mvn clean test "-DsuiteXmlFile=testng-regression.xml"

      - name: Upload Regression Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: regression-test-reports
          path: |
            target/surefire-reports/
            target/ExtentReport.html
            screenshot/